spring:
  h2: 
    console: 
      enabled:  true 
      path: /h2
  jpa:  
    database-platform:  org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: false
    generate-ddl: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
    
server: 
  port: 8081
  error:
    include-stacktrace: never
